---
apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: db
  labels:
    app: mysql
spec:
  containers:
    - name: container-mysql
      image: 717693563238.dkr.ecr.us-east-1.amazonaws.com/mysql:071180f
      ports:
        - containerPort: 3306
