---
apiVersion: v1
kind: Service
metadata:
  name: service-webapp
  namespace: app
spec:
  selector:
    app: employee
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
