---
apiVersion: v1
kind: Pod
metadata:
  name: pod-webapp
  namespace: app
  labels:
    app: employee
spec:
  containers:
    - name: container-webapp
      image: 717693563238.dkr.ecr.us-east-1.amazonaws.com/webapp:071180f
      ports:
        - containerPort: 80
