---
apiVersion: v1
kind: Pod
metadata:
  name: pod-webapp
  namespace: app
  labels:
    app: employees
spec:
  containers:
    - name: container-webapp
      image: 717693563238.dkr.ecr.us-east-1.amazonaws.com/webapp:071180f
      ports:
        - containerPort: 80
      env:
        - name: DBHOST
          value: "service-mysql.db.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"
