---
apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
  namespace: app
spec:
  selector:
    app: employees
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
